services:
  # Base network config
  network-deploy-service:
    networks:
      - eazybank

  # Base microservice config (shared by all microservices)
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      # All microservices will fetch config from Config Server

  # Config Server specific config
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
