services:
  configserver:
    image: "sohan91/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "sohan91/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "sohan91/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      EUREKA_INSTANCE_INSTANCE_ID: "accounts-ms:8080"
      EUREKA_INSTANCE_HOSTNAME: "accounts-ms"
      EUREKA_INSTANCE_NON_SECURE_PORT: "8080"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "sohan91/loans:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "loans"
      EUREKA_INSTANCE_INSTANCE_ID: "loans-ms:8090"
      EUREKA_INSTANCE_HOSTNAME: "loans-ms"
      EUREKA_INSTANCE_NON_SECURE_PORT: "8090"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans2:
    image: "sohan91/loans:s8"
    container_name: loans-ms2
    ports:
      - "8091:8091"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "loans"
      EUREKA_INSTANCE_INSTANCE_ID: "loans-ms2:8091"
      EUREKA_INSTANCE_HOSTNAME: "loans-ms2"
      EUREKA_INSTANCE_NON_SECURE_PORT: "8091"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "sohan91/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "cards"
      EUREKA_INSTANCE_INSTANCE_ID: "cards-ms:9000"
      EUREKA_INSTANCE_HOSTNAME: "cards-ms"
      EUREKA_INSTANCE_NON_SECURE_PORT: "9000"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: "bridge"