services:

  # ------------------ BASE NETWORK ------------------
  network-deploy-service:
    networks:
      - eazybank

  # ------------------ DATABASE BASE CONFIG ------------------
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: roots   # Consistent password for all DBs
    networks:
      - eazybank

  # ------------------ BASE CONFIG FOR MICROSERVICES ------------------
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  # ------------------ CONFIG SERVER BASE ------------------
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: roots
    networks:
      - eazybank

networks:
  eazybank:
    driver: bridge