spring:
  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:

#          search-locations: "file:///D:/SOHAN/MicroServices/section6-Config-Management/cloud-config-yml-files"
#
        git:
          uri: https://github.com/sohan91/Microservices-Demo.git
          search-paths: section6-Config-Management/cloud-config-yml-files
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: "8071"


